Get File Hash.ps1
=> Pull request with type [CREATE] for user [silveyy] and object type [Script] - titled [Get File Hash]

Check OS Versions.ps1
=> Pull request with type [CREATE] for user [ehsansccm] and object type [Script] - titled [Check OS Versions]

Who's doing Interactive Logon.ps1
=> Pull request with type [CREATE] for user [kmyrup] and object type [Script] - titled [Who's doing Interactive Logon]

Task Sequence 2 test.xml
=> Pull request with type [CREATE] for user [sihlamMSFT] and object type [TaskSequence] - titled [Task Sequence 2 test]

Task Sequence 3 test.xml
=> Pull request with type [CREATE] for user [sihlamMSFT] and object type [TaskSequence] - titled [Task Sequence 3 test]

Empty Test Report.rdl
=> Pull request with type [CREATE] for user [DavidHoeMSFT] and object type [Report] - titled [Empty Test Report]

new report test.rdl
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Report] - titled [new report test]

PerfScale_sensoreval_remia.ps1
=> Pull request with type [CREATE] for user [silveyy] and object type [Script] - titled [PerfScale_sensoreval_remia]

OSD Windows 10 Release ID.ps1
=> Pull request with type [CREATE] for user [silveyy] and object type [Script] - titled [OSD Windows 10 Release ID]

get top 2 process.ps1
=> Pull request with type [CREATE] for user [silveyy] and object type [Script] - titled [get top 2 process]

pivot3.ps1
=> Pull request with type [CREATE] for user [silveyy] and object type [Script] - titled [pivot3]

Demo - fix regkey.ps1
=> Pull request with type [CREATE] for user [silveyy] and object type [Script] - titled [Demo - fix regkey]

MBAM_Friday.ps1
=> Pull request with type [CREATE] for user [silveyy] and object type [Script] - titled [MBAM_Friday]

Test Query 2
=> Pull request with type [CREATE] for user [silveyy] and object type [CMPivotQuery] - titled [Test Query 2]

objects/silveyy/Script/Disable_SMBv1_3.ps1
=> Pull request with type [CREATE] for user [silveyy] and object type [Script] - titled [Disable_SMBv1_3]

objects/silveyy/TaskSequence/Disable_SMBv1_3.xml
=> Pull request with type [CREATE] for user [silveyy] and object type [TaskSequence] - titled [Disable_SMBv1_3]

objects/Script/Dogfood Office Log Tables.ps1
=> Pull request with type [CREATE] for user [silveyy] and object type [Script] - titled [Dogfood Office Log Tables]

objects/TaskSequence/5739145 Nested with no steps - Child.xml
=> Pull request with type [CREATE] for user [silveyy] and object type [TaskSequence] - titled [5739145 Nested with no steps - Child]

objects/TaskSequence/Task Sequence test.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [TaskSequence] - titled [Task Sequence test]

objects/Script/8NameFallback.ps1
=> Pull request with type [CREATE] for user [silveyy] and object type [Script] - titled [8NameFallback]

objects/ConfigurationItem/abc.xml
=> Pull request with type [CREATE] for user [silveyy] and object type [ConfigurationItem] - titled [abc]

objects/ConfigurationItem/Test Community hub Contribute Empty CI 1.xml
=> Pull request with type [CREATE] for user [DavidHoeMSFT] and object type [ConfigurationItem] - titled [Test Community hub Contribute Empty CI 1]

objects/Script/Hub test 1.ps1
=> Pull request with type [CREATE] for user [lindsayShap] and object type [Script] - titled [Hub test 1]

objects/TaskSequence/Notify Anton.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [TaskSequence] - titled [Notify Anton]

objects/Application/HUB test app.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [Application] - titled [HUB test app]

objects/TaskSequence/SimpleTS2.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [TaskSequence] - titled [SimpleTS2]

objects/Application/No Gravity.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [Application] - titled [No Gravity]

objects/ConfigurationItem/Example OS CI.xml
=> Pull request with type [CREATE] for user [kmyrup] and object type [ConfigurationItem] - titled [Example OS CI]

objects/ConfigurationItem/Example Appliation CI.xml
=> Pull request with type [CREATE] for user [kmyrup] and object type [ConfigurationItem] - titled [Example Appliation CI]

objects/ConfigurationItem/2006 E14 CI.xml
=> Pull request with type [CREATE] for user [kmyrup] and object type [ConfigurationItem] - titled [2006 E14 CI]

objects/CMPivotQuery/Shows when devices have restarted in the last seven days
=> Pull request with type [CREATE] for user [kmyrup] and object type [CMPivotQuery] - titled [Shows when devices have restarted in the last seven days]

objects/TaskSequence/SimpleTS2.xml
=> Pull request with type [UPDATE] for user [lindsayShap] and object type [TaskSequence] - titled [SimpleTS2]

objects/Script/Boot Time v6.ps1
=> Pull request with type [CREATE] for user [lindsayShap] and object type [Script] - titled [Boot Time v6]

objects/ConfigurationItem/Registry CI.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [Registry CI]

objects/Application/No Gravity.xml
=> Pull request with type [UPDATE] for user [lindsayShap] and object type [Application] - titled [No Gravity]

objects/ConfigurationItem/ci_regKey_1.xml
=> Pull request with type [UPDATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [ci_regKey_1]

objects/Script/Hub test 1.ps1
=> Pull request with type [UPDATE] for user [lindsayShap] and object type [Script] - titled [Hub test 1]

objects/ConfigurationItem/Registry CI.xml
=> Pull request with type [UPDATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [Registry CI]

objects/ConfigurationItem/liharris_test_txt_file.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [liharris_test_txt_file]

objects/ConfigurationItem/liharris_test_1.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [liharris_test_1]

objects/ConfigurationItem/liharris_test_2.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [liharris_test_2]

objects/ConfigurationItem/liharris_test_txt_file.xml
=> Pull request with type [UPDATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [liharris_test_txt_file]

objects/ConfigurationItem/liharris_test_1.xml
=> Pull request with type [UPDATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [liharris_test_1]

objects/Script/Reset Client Policy.ps1
=> Pull request with type [CREATE] for user [koala1985] and object type [Script] - titled [Reset Client Policy]

objects/ConfigurationItem/CI test for update.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [CI test for update]

objects/CMPivotQuery/CMPivotQueryTest
=> Pull request with type [CREATE] for user [v-shrdes] and object type [CMPivotQuery] - titled [CMPivotQueryTest]

objects/Application/test application for update scenario.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Application] - titled [test application for update scenario]

objects/ConfigurationItem/Empty Community Hub CI One.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [Empty Community Hub CI One]

objects/ConfigurationItem/CI FOR TEST.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [CI FOR TEST]

objects/ConfigurationItem/liharris_test_file_4.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [liharris_test_file_4]

objects/ConfigurationItem/CI test for update.xml
=> Pull request with type [UPDATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [CI test for update]

objects/Application/test app.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Application] - titled [test app]

objects/Script/Get File Hash.ps1
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Script] - titled [Get File Hash]

objects/Script/Get File Hash.ps1
=> Pull request with type [UPDATE] for user [v-shrdes] and object type [Script] - titled [Get File Hash]

objects/CMPivotQuery/Test Query 2
=> Pull request with type [CREATE] for user [v-shrdes] and object type [CMPivotQuery] - titled [Test Query 2]

objects/TaskSequence/Task Sequence 1 test.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [TaskSequence] - titled [Task Sequence 1 test]

objects/Application/admin.manage.contoso.com.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Application] - titled [admin.manage.contoso.com]

objects/TaskSequence/Task Sequence 1 test.xml
=> Pull request with type [UPDATE] for user [v-shrdes] and object type [TaskSequence] - titled [Task Sequence 1 test]

objects/ConfigurationItem/CI FOR TEST.xml
=> Pull request with type [UPDATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [CI FOR TEST]

objects/Script/script update.ps1
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Script] - titled [script update]

objects/Report/new report test test.rdl
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Report] - titled [new report test test]

objects/ConfigurationItem/update cI test 2002.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [update cI test 2002]

objects/TaskSequence/任务序列 1 Update test task sequence.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [TaskSequence] - titled [任务序列 1 Update test task sequence]

objects/Application/update app test 2002.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Application] - titled [update app test 2002]

objects/TaskSequence/Task Sequence 1.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [TaskSequence] - titled [Task Sequence 1]

objects/ConfigurationItem/update test ci.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [update test ci]

objects/Report/2006 test report 1.rdl
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Report] - titled [2006 test report 1]

objects/Script/script update.ps1
=> Pull request with type [UPDATE] for user [v-shrdes] and object type [Script] - titled [script update]

objects/TaskSequence/2010 test task sequence.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [TaskSequence] - titled [2010 test task sequence]

objects/TaskSequence/2010 test task sequence.xml
=> Pull request with type [UPDATE] for user [v-shrdes] and object type [TaskSequence] - titled [2010 test task sequence]

objects/TaskSequence/liharris_test_ts_hub.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [TaskSequence] - titled [liharris_test_ts_hub]

objects/ConfigurationItem/liharris_test_file_4.xml
=> Pull request with type [UPDATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [liharris_test_file_4]

objects/ConfigurationItem/Frogs.xml
=> Pull request with type [CREATE] for user [kmyrup] and object type [ConfigurationItem] - titled [Frogs]

objects/ConfigurationItem/Cats.xml
=> Pull request with type [CREATE] for user [kmyrup] and object type [ConfigurationItem] - titled [Cats]

objects/Report/liharrris empty report.rdl
=> Pull request with type [CREATE] for user [lindsayShap] and object type [Report] - titled [liharrris empty report]

objects/Report/empty report 4.rdl
=> Pull request with type [CREATE] for user [lindsayShap] and object type [Report] - titled [empty report 4]

objects/Report/liharris empty report 3.rdl
=> Pull request with type [CREATE] for user [lindsayShap] and object type [Report] - titled [liharris empty report 3]

objects/Report/Empty Test Report 3.rdl
=> Pull request with type [CREATE] for user [lindsayShap] and object type [Report] - titled [Empty Test Report 3]

objects/Report/liharris test report2.rdl
=> Pull request with type [CREATE] for user [lindsayShap] and object type [Report] - titled [liharris test report2]

objects/Script/Disable_SMBv1_3.ps1
=> Pull request with type [CREATE] for user [lindsayShap] and object type [Script] - titled [Disable_SMBv1_3]

objects/Report/empty report 4.3.rdl
=> Pull request with type [CREATE] for user [lindsayShap] and object type [Report] - titled [empty report 4.3]

objects/Report/2010 report.rdl
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Report] - titled [2010 report]

objects/ConfigurationItem/update test ci.xml
=> Pull request with type [UPDATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [update test ci]

objects/ConfigurationItem/StormFather.xml
=> Pull request with type [CREATE] for user [kmyrup] and object type [ConfigurationItem] - titled [StormFather]

objects/ConfigurationItem/empty CI for testing bug.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [empty CI for testing bug]

objects/ConfigurationItem/ci_regKey_5.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [ci_regKey_5]

objects/Application/Acrobat Reader DC 1502320056.xml
=> Pull request with type [CREATE] for user [ehsansccm] and object type [Application] - titled [Acrobat Reader DC 1502320056]

objects/Application/Hub App With Content Test.xml
=> Pull request with type [CREATE] for user [ehsansccm] and object type [Application] - titled [Hub App With Content Test]

objects/Report/report test.rdl
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Report] - titled [report test]

objects/ConfigurationItem/CI1.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [CI1]

objects/ConfigurationItem/liharris_new_ci_test.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [liharris_new_ci_test]

objects/Report/2002 report.rdl
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Report] - titled [2002 report]

objects/Script/script for update .ps1
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Script] - titled [script for update ]

objects/ConfigurationItem/CI for update.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [CI for update]

objects/TaskSequence/Task Sequence for update test.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [TaskSequence] - titled [Task Sequence for update test]

objects/Application/test qpp 2002.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Application] - titled [test qpp 2002]

objects/Application/test qpp 2006.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Application] - titled [test qpp 2006]

objects/ConfigurationItem/CI for update.xml
=> Pull request with type [UPDATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [CI for update]

objects/Script/script for update .ps1
=> Pull request with type [UPDATE] for user [v-shrdes] and object type [Script] - titled [script for update ]

objects/ConfigurationItem/CI 2002 update.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [CI 2002 update]

objects/Application/Update scenario 2002 Application.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Application] - titled [Update scenario 2002 Application]

objects/TaskSequence/任务序列 1 Update 2002 app.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [TaskSequence] - titled [任务序列 1 Update 2002 app]

objects/CMPivotQuery/cmpivot 2010
=> Pull request with type [CREATE] for user [v-shrdes] and object type [CMPivotQuery] - titled [cmpivot 2010]

objects/ConfigurationItem/CI 2010.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [CI 2010]

objects/TaskSequence/Task Sequence 2010 test.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [TaskSequence] - titled [Task Sequence 2010 test]

objects/Application/constosso 2010 app test.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Application] - titled [constosso 2010 app test]

objects/ConfigurationItem/liharris_new_2010_txtFile.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [liharris_new_2010_txtFile]

objects/ConfigurationItem/Good CI.xml
=> Pull request with type [CREATE] for user [cmearlyadopter] and object type [ConfigurationItem] - titled [Good CI]

objects/ConfigurationItem/aaa.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [aaa]

objects/ConfigurationItem/liharris_test_txt_fileRBAC.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [liharris_test_txt_fileRBAC]

objects/Report/Empty Test Report.rdl
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Report] - titled [Empty Test Report]

objects/ConfigurationItem/CI 2010 for 2012.xml
=> Pull request with type [UPDATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [CI 2010 for 2012]

objects/TaskSequence/new Task Sequence 2010 for 2012.xml
=> Pull request with type [UPDATE] for user [v-shrdes] and object type [TaskSequence] - titled [new Task Sequence 2010 for 2012]

objects/Script/script 2006 for 2012.ps1
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Script] - titled [script 2006 for 2012]

objects/Application/app 2006 for 2012.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Application] - titled [app 2006 for 2012]

objects/TaskSequence/Task Sequence 2006 for 2012 test.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [TaskSequence] - titled [Task Sequence 2006 for 2012 test]

objects/Report/report 2006 for 2012.rdl
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Report] - titled [report 2006 for 2012]

objects/ConfigurationItem/CI 2006 for 2012.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [CI 2006 for 2012]

objects/ConfigurationItem/CI 2006 for 2012.xml
=> Pull request with type [UPDATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [CI 2006 for 2012]

objects/Report/report 2010 for 2012.rdl
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Report] - titled [report 2010 for 2012]

objects/Application/Performance Diagnostic.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Application] - titled [Performance Diagnostic]

objects/ConfigurationItem/32 K CI.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [32 K CI]

objects/ConfigurationItem/See Eye.xml
=> Pull request with type [CREATE] for user [cmearlyadopter] and object type [ConfigurationItem] - titled [See Eye]

objects/ConfigurationItem/See Eye.xml
=> Pull request with type [UPDATE] for user [cmearlyadopter] and object type [ConfigurationItem] - titled [See Eye]

objects/Application/Orca.xml
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [Application] - titled [Orca]

objects/Baseline/liharris_test_baseline2.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [Baseline] - titled [liharris_test_baseline2]

objects/Baseline/liharris_test_Baseline1.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [Baseline] - titled [liharris_test_Baseline1]

objects/ConfigurationItem/liharris_test_hub_3.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [liharris_test_hub_3]

objects/Baseline/liharris_test_baseline2.xml
=> Pull request with type [UPDATE] for user [lindsayShap] and object type [Baseline] - titled [liharris_test_baseline2]

objects/Script/Test2002.ps1
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [Script] - titled [Test2002]

objects/Script/Test2006.ps1
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [Script] - titled [Test2006]

objects/Script/test2010.ps1
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [Script] - titled [test2010]

objects/ConfigurationItem/CI2002.xml
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [ConfigurationItem] - titled [CI2002]

objects/ConfigurationItem/CI2010.xml
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [ConfigurationItem] - titled [CI2010]

objects/ConfigurationItem/CI2006.xml
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [ConfigurationItem] - titled [CI2006]

objects/Report/Administration activity log.rdl
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [Report] - titled [Administration activity log]

objects/Report/Report2010.rdl
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [Report] - titled [Report2010]

objects/Report/Test2006.rdl
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [Report] - titled [Test2006]

objects/Report/2002.rdl
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [Report] - titled [2002]

objects/TaskSequence/TS2010Test.xml
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [TaskSequence] - titled [TS2010Test]

objects/TaskSequence/TS2002Test.xml
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [TaskSequence] - titled [TS2002Test]

objects/TaskSequence/TS2006Test.xml
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [TaskSequence] - titled [TS2006Test]

objects/Application/App2006Test.xml
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [Application] - titled [App2006Test]

objects/Application/App2010Test.xml
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [Application] - titled [App2010Test]

objects/CMPivotQuery/CmPivot2002
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [CMPivotQuery] - titled [CmPivot2002]

objects/CMPivotQuery/PIvot2006
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [CMPivotQuery] - titled [PIvot2006]

objects/CMPivotQuery/PIvot2010
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [CMPivotQuery] - titled [PIvot2010]

objects/Report/Report2010_2002.rdl
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [Report] - titled [Report2010_2002]

objects/Application/CCM Framework Tools.xml
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [Application] - titled [CCM Framework Tools]

objects/ConfigurationItem/CI2010_2002.xml
=> Pull request with type [UPDATE] for user [AnsariHubTest] and object type [ConfigurationItem] - titled [CI2010_2002]

objects/ConfigurationItem/CI test 2010 for update.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [ConfigurationItem] - titled [CI test 2010 for update]

objects/Application/empty.xml
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Application] - titled [empty]

objects/Application/empty.xml
=> Pull request with type [UPDATE] for user [v-shrdes] and object type [Application] - titled [empty]

objects/Application/AnsariApp.xml
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [Application] - titled [AnsariApp]

objects/Application/EMPTY21.xml
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [Application] - titled [EMPTY21]

objects/Report/test 2010 new.rdl
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Report] - titled [test 2010 new]

objects/Report/nez 2010 report.rdl
=> Pull request with type [CREATE] for user [v-shrdes] and object type [Report] - titled [nez 2010 report]

objects/ConfigurationItem/CI2006.xml
=> Pull request with type [UPDATE] for user [AnsariHubTest] and object type [ConfigurationItem] - titled [CI2006]

objects/TaskSequence/TS2006Test_Update.xml
=> Pull request with type [UPDATE] for user [AnsariHubTest] and object type [TaskSequence] - titled [TS2006Test_Update]

objects/Report/AnsariEmptyReport.rdl
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [Report] - titled [AnsariEmptyReport]

objects/Baseline/liharris_test_Baseline1.xml
=> Pull request with type [UPDATE] for user [lindsayShap] and object type [Baseline] - titled [liharris_test_Baseline1]

objects/ConfigurationItem/liharris_test_hub_3.xml
=> Pull request with type [UPDATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [liharris_test_hub_3]

tools/ExtensionDownloader.ps1
Update ExtensionDownloader.ps1 to fix a few small things.
=> Update ExtensionDownloader.ps1 - bug fixes

objects/Application/Test MSI #2 replace DT location.xml
=> Pull request with type [CREATE] for user [ehsansccm] and object type [Application] - titled [Test MSI #2 replace DT location]

objects/ConsoleExtension/Right Click Twos-CodeSign-Policy.xml, objects/ConsoleExtension/Right Click Twos.json
=> Pull request with type [CREATE] for user [sihlamMSFT] and object type [ConsoleExtension] - titled [Right Click Twos]

objects/ConsoleExtension/Right Click Twos.json
=> Pull request with type [UPDATE] for user [sihlamMSFT] and object type [ConsoleExtension] - titled [Right Click Twos]

objects/ConfigurationItem/Cool Reg CI.xml
=> Pull request with type [CREATE] for user [cmearlyadopter] and object type [ConfigurationItem] - titled [Cool Reg CI]

objects/Baseline/Cool Reg Baseline.xml
=> Pull request with type [CREATE] for user [cmearlyadopter] and object type [Baseline] - titled [Cool Reg Baseline]

objects/Baseline/Nested.xml
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [Baseline] - titled [Nested]

objects/ConfigurationItem/Version CI.xml
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [ConfigurationItem] - titled [Version CI]

objects/CMPivotQuery/2104_2103
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [CMPivotQuery] - titled [2104_2103]

objects/Report/2104_2103_New.rdl
=> Pull request with type [CREATE] for user [AnsariHubTest] and object type [Report] - titled [2104_2103_New]

objects/ConfigurationItem/Version CI.xml
=> Pull request with type [UPDATE] for user [AnsariHubTest] and object type [ConfigurationItem] - titled [Version CI]

CODEOWNERS
restrict approval on certain files.
=> Create CODEOWNERS for selfhost

objects/Script/CMTraceUpdate.ps1
=> Pull request with type [CREATE] for user [koala1985] and object type [Script] - titled [CMTraceUpdate]

objects/ConfigurationItem/CI to download.xml
=> Pull request with type [CREATE] for user [cmearlyadopter] and object type [ConfigurationItem] - titled [CI to download]

objects/ConfigurationItem/Update CI 14 version 1.xml
=> Pull request with type [CREATE] for user [DavidHoeMSFT] and object type [ConfigurationItem] - titled [Update CI 14 version 1]

objects/ConfigurationItem/CI_2103_version1.xml
=> Pull request with type [CREATE] for user [Rahul2200] and object type [ConfigurationItem] - titled [CI_2103_version1]

objects/ConfigurationItem/CI_2103_version1.xml
=> Pull request with type [UPDATE] for user [Rahul2200] and object type [ConfigurationItem] - titled [CI_2103_version1]

objects/ConsoleExtension/2105 Extension-Codesign-Policy.xml, objects/ConsoleExtension/2105 Extension.json
=> Pull request with type [UPDATE] for user [kmyrup] and object type [ConsoleExtension] - titled [2105 Extension]

objects/ConfigurationItem/2103_2106_CI_curated.xml
=> Pull request with type [CREATE] for user [Rahul2200] and object type [ConfigurationItem] - titled [2103_2106_CI_curated]

objects/Script/2103_2106_script_curated.ps1
=> Pull request with type [UPDATE] for user [Rahul2200] and object type [Script] - titled [2103_2106_script_curated]

objects/Application/2103_2106_app_curated.xml
=> Pull request with type [UPDATE] for user [Rahul2200] and object type [Application] - titled [2103_2106_app_curated]

objects/ConfigurationItem/2107_2010_CI.xml
=> Pull request with type [CREATE] for user [AnsariTan] and object type [ConfigurationItem] - titled [2107_2010_CI]

objects/ConsoleExtension/GoodExtension-CodeSign-Policy.xml, objects/ConsoleExtension/GoodExtension.json
=> Pull request with type [CREATE] for user [cmearlyadopter] and object type [ConsoleExtension] - titled [GoodExtension]

objects/CMPivotQuery/Count of Intel Chip Families
=> Pull request with type [CREATE] for user [v-aakapi] and object type [CMPivotQuery] - titled [Count of Intel Chip Families]

objects/ConfigurationItem/E20_win11_ci1.xml
=> Pull request with type [CREATE] for user [lindsayshapleigh] and object type [ConfigurationItem] - titled [E20_win11_ci1]

objects/ConfigurationItem/2109_2010.xml
=> Pull request with type [CREATE] for user [AnsariTan] and object type [ConfigurationItem] - titled [2109_2010]

objects/ConsoleExtension/RCT-2109 Test-CodeSign-Policy.xml, objects/ConsoleExtension/RCT-2109 Test.json
=> Pull request with type [CREATE] for user [cmearlyadopter] and object type [ConsoleExtension] - titled [RCT-2109 Test]

objects/ConfigurationItem/CI_six.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [CI_six]

objects/ConfigurationItem/CI_one.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [CI_one]

objects/ConfigurationItem/CI_two.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [CI_two]

objects/ConfigurationItem/CI_three.xml
=> Pull request with type [CREATE] for user [lindsayShap] and object type [ConfigurationItem] - titled [CI_three]

objects/ConfigurationItem/2110_CI_2002_2006.xml
=> Pull request with type [CREATE] for user [AnsariTan] and object type [ConfigurationItem] - titled [2110_CI_2002_2006]

objects/Script/Rename.ps1
=> Pull request with type [CREATE] for user [cmearlyadopter] and object type [Script] - titled [Rename]

objects/Script/StartOver.ps1
=> Pull request with type [CREATE] for user [cmearlyadopter] and object type [Script] - titled [StartOver]

objects/ConsoleExtension/2112 selfhost extension.json
=> Pull request with type [CREATE] for user [cmearlyadopter] and object type [ConsoleExtension] - titled [2112 selfhost extension]

objects/ConfigurationItem/CI from 2010 for 2112.xml
=> Pull request with type [CREATE] for user [sethlam] and object type [ConfigurationItem] - titled [CI from 2010 for 2112]

objects/TaskSequence/TS from 2010 for 2112.xml
=> Pull request with type [CREATE] for user [sethlam] and object type [TaskSequence] - titled [TS from 2010 for 2112]

objects/Application/communityhubtest.microsoft.com.xml
=> Pull request with type [CREATE] for user [cmearlyadopter] and object type [Application] - titled [communityhubtest.microsoft.com]

Communityhub/ConfigurationItem/TestChildCI.xml
=> Pull request with type [CREATE] for user [Jing099] and object type [ConfigurationItem] - titled [TestChildCI]

Communityhub/Baseline/TestBaselineWithCI.xml
=> Pull request with type [CREATE] for user [Jing099] and object type [Baseline] - titled [TestBaselineWithCI]

Communityhub/ConfigurationItem/TestCI12809714.xml
=> Pull request with type [CREATE] for user [Jing099] and object type [ConfigurationItem] - titled [TestCI12809714]

Communityhub/Baseline/TestBaseline12809714.xml
=> Pull request with type [CREATE] for user [Jing099] and object type [Baseline] - titled [TestBaseline12809714]

Communityhub/ConfigurationItem/TestCI12809714_3.xml
=> Pull request with type [CREATE] for user [Jing099] and object type [ConfigurationItem] - titled [TestCI12809714_3]

Communityhub/Baseline/TestBaseline12809714_3.xml
=> Pull request with type [CREATE] for user [Jing099] and object type [Baseline] - titled [TestBaseline12809714_3]

Communityhub/ConfigurationItem/TestCI12809714_fix.xml
=> Pull request with type [CREATE] for user [Jing099] and object type [ConfigurationItem] - titled [TestCI12809714_fix]

Communityhub/Baseline/TestBaseline12809714_Fix.xml
=> Pull request with type [CREATE] for user [Jing099] and object type [Baseline] - titled [TestBaseline12809714_Fix]

Communityhub/ConfigurationItem/TestCI12809714_55.xml
=> Pull request with type [CREATE] for user [Jing099] and object type [ConfigurationItem] - titled [TestCI12809714_55]

Communityhub/Baseline/TestBaseline12809714_55.xml
=> Pull request with type [CREATE] for user [Jing099] and object type [Baseline] - titled [TestBaseline12809714_55]

Communityhub/ConfigurationItem/Hub_ci_1_2203.xml
=> Pull request with type [CREATE] for user [lindsayshapleigh] and object type [ConfigurationItem] - titled [Hub_ci_1_2203]

Communityhub/Script/Original Script Name.ps1
=> Pull request with type [CREATE] for user [cmearlyadopter] and object type [Script] - titled [Original Script Name]

Communityhub/Script/Script A.ps1
=> Pull request with type [CREATE] for user [cmearlyadopter] and object type [Script] - titled [Script A]

Communityhub/ConfigurationItem/2108_ci1.xml.xml
=> Pull request with type [CREATE] for user [lindsayshapleigh] and object type [ConfigurationItem] - titled [2108_ci1]

Communityhub/CMPivotQuery/CMPivotQueryTest
=> Pull request with type [CREATE] for user [cmearlyadopter] and object type [CMPivotQuery] - titled [CMPivotQueryTest]

Communityhub/CMPivotQuery/cmpivot_communityHub_one_More
=> Pull request with type [CREATE] for user [KevinGuanHub] and object type [CMPivotQuery] - titled [cmpivot_communityHub_one_More]
